version: "3.8"
services:
  web:
    image: todo-web-app
    environment: 
      REACT_APP_API_URL: http://localhost:3001/api
    depends_on:
      - todo-api
    ports:
      - "3000:3000"
  todo-api:
    image: todo-api
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  mongo:
    image: mongo
    restart: always
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password